import { TEXT_CASE } from './textCase';
import { TEXT_HORIZONTAL_ALIGN, TEXT_VERTICAL_ALIGN } from './textAlign';
import { BACKGROUND_TYPE, BACKGROUND_PAGE_TYPE } from './backgroundType';
import { PRINT_PAGE_SIZE } from './canvas';
import { IMAGE_LOCAL } from './image';
import { SVG_FILL_MODE } from './svgFillMode';
import { POSITION_ORIGIN } from './origin';

export const OBJECT_MIN_SIZE = 0.5; // inch

export const DEFAULT_SVG = {
  WIDTH: 1.5,
  HEIGHT: 1.5
};

export const DEFAULT_PROP = {
  OPACITY: 1,
  COLOR: '#000000',
  MIN_POSITION: -100,
  MAX_POSITION: 100,
  MIN_SIZE: 0.5,
  MAX_SIZE: 60,
  BORDER: {
    FILL: false,
    STROKE: '#000000',
    STROKE_WIDTH: 0,
    STROKE_DASH_ARRAY: [],
    STROKE_LINE_CAP: 'solid'
  }
};

export const DEFAULT_COORD = {
  X: PRINT_PAGE_SIZE.PDF_WIDTH * 0.5, // center
  Y: PRINT_PAGE_SIZE.PDF_HEIGHT * 0.5, // middle
  ROTATION: 0
};

export const DEFAULT_ORIGIN = {
  X: POSITION_ORIGIN.LEFT,
  Y: POSITION_ORIGIN.TOP
};

export const DEFAULT_SHADOW = {
  DROP_SHADOW: false,
  BLUR: 5,
  OFFSET: 2,
  OPACITY: 0.5,
  ANGLE: 270,
  COLOR: DEFAULT_PROP.COLOR
};

export const DEFAULT_TEXT = {
  TEXT: 'Text',
  COORD: {
    ...DEFAULT_COORD
  },
  SIZE: {
    width: 0,
    height: 0
  },
  TEXT_CASE: TEXT_CASE.NONE,
  STYLE_ID: 'default',
  FONT_FAMILY: 'Arial',
  FONT_SIZE: 60,
  IS_BOLD: false,
  IS_ITALIC: false,
  IS_UNDERLINE: false,
  ALIGNMENT: {
    HORIZONTAL: TEXT_HORIZONTAL_ALIGN.LEFT,
    VERTICAL: TEXT_VERTICAL_ALIGN.TOP
  },
  LETTER_SPACING: 0,
  LINE_SPACING: 0,
  LINE_HEIGHT: 1,
  COLUMN: 1,
  ORIGIN: {
    ...DEFAULT_ORIGIN
  },
  LOCK_UNI_SCALE: false,
  OPACITY: DEFAULT_PROP.OPACITY,
  EDITING_BORDER_COLOR: 'transparent',
  BORDER: DEFAULT_PROP.BORDER,
  SHADOW: {
    ...DEFAULT_SHADOW
  },
  IS_CONSTRAIN: false,
  MIN_SIZE: DEFAULT_PROP.MIN_SIZE,
  MAX_SIZE: DEFAULT_PROP.MAX_SIZE,
  MIN_POSITION: DEFAULT_PROP.MIN_POSITION,
  MAX_POSITION: DEFAULT_PROP.MAX_POSITION
};

export const DEFAULT_CLIP_ART = {
  COORD: {
    ...DEFAULT_COORD
  },
  COLOR: DEFAULT_PROP.COLOR,
  ORIGIN: {
    ...DEFAULT_ORIGIN
  },
  OPACITY: DEFAULT_PROP.OPACITY,
  WIDTH: DEFAULT_SVG.WIDTH, // inch
  HEIGHT: DEFAULT_SVG.HEIGHT, // inch
  MIN_SIZE: DEFAULT_PROP.MIN_SIZE,
  MAX_SIZE: DEFAULT_PROP.MAX_SIZE,
  FILL_MODE: SVG_FILL_MODE.FILL,
  IS_CONSTRAIN: true,
  MIN_POSITION: DEFAULT_PROP.MIN_POSITION,
  MAX_POSITION: DEFAULT_PROP.MAX_POSITION,
  SHADOW: {
    ...DEFAULT_SHADOW
  }
};

export const DEFAULT_IMAGE = {
  category: 'Cover',
  name: '',
  thumbnail: IMAGE_LOCAL.PLACE_HOLDER,
  imageUrl: IMAGE_LOCAL.PLACE_HOLDER
};

export const DEFAULT_BACKGROUND = {
  BACKGROUND_TYPE: BACKGROUND_TYPE.THEME.id,
  PAGE_TYPE: BACKGROUND_PAGE_TYPE.FULL_PAGE.id,
  IS_LEFT: true
};

export const DEFAULT_SHAPE = {
  WIDTH: DEFAULT_SVG.WIDTH,
  HEIGHT: DEFAULT_SVG.HEIGHT,
  MIN_SIZE: DEFAULT_PROP.MIN_SIZE,
  MAX_SIZE: DEFAULT_PROP.MAX_SIZE,
  MIN_POSITION: DEFAULT_PROP.MIN_POSITION,
  MAX_POSITION: DEFAULT_PROP.MAX_POSITION,
  SHADOW: {
    ...DEFAULT_SHADOW
  },
  ORIGIN: {
    ...DEFAULT_ORIGIN
  },
  FILL_MODE: SVG_FILL_MODE.FILL,
  BORDER: DEFAULT_PROP.BORDER
};
