export const MAPPING_OBJECT_STATE_UNASSIGNED = 'UNASSIGNED';
export const MAPPING_OBJECT_STATE_MAPPING = 'MAPPING';
export const MAPPING_OBJECT_STATE_MAPPED = 'MAPPED';

export const OVERLAY_BACKGROUND_COLOR = 'rgba(88,89,91,0.4)';
