export const MODULE_NAME = 'book';

const _GETTERS = {
  BOOK_DETAIL: 'bookDetail',
  BOOK_ID: 'bookId',
  SECTIONS: 'sections',
  SELECTED_OBJECT_TYPE: 'selectedObjectType',
  IS_OPEN_MENU_PROPERTIES: 'isOpenMenuProperties',
  GET_BOOK_DATES: 'getBookDates'
};

export const GETTERS = {
  SECTIONS: `${MODULE_NAME}/${_GETTERS.SECTIONS}`,
  BOOK_DETAIL: `${MODULE_NAME}/${_GETTERS.BOOK_DETAIL}`,
  BOOK_ID: `${MODULE_NAME}/${_GETTERS.BOOK_ID}`,
  SELECTED_OBJECT_TYPE: `${MODULE_NAME}/${_GETTERS.SELECTED_OBJECT_TYPE}`,
  IS_OPEN_MENU_PROPERTIES: `${MODULE_NAME}/${_GETTERS.IS_OPEN_MENU_PROPERTIES}`,
  GET_BOOK_DATES: `${MODULE_NAME}/${_GETTERS.GET_BOOK_DATES}`
};

const _ACTIONS = {
  GET_BOOK: 'getBook'
};

export const ACTIONS = {
  GET_BOOK: `${MODULE_NAME}/${_ACTIONS.GET_BOOK}`
};

const _MUTATES = {
  UPDATE_SECTIONS: 'updateSections',
  UPDATE_SECTION_POSITION: 'updateSectionPosition',
  UPDATE_SHEETS: 'updateSheets',
  UPDATE_SHEET_POSITION: 'updateSheetPosition',
  GET_BOOK_SUCCESS: 'getBookSuccess',
  SET_OBJECT_TYPE_SELECTED: 'setObjectTypeSelected',
  TOGGLE_MENU_PROPERTIES: 'toggleMenuProperties'
};

export const MUTATES = {
  GET_BOOK_SUCCESS: `${MODULE_NAME}/${_MUTATES.GET_BOOK_SUCCESS}`,
  UPDATE_SECTIONS: `${MODULE_NAME}/${_MUTATES.UPDATE_SECTIONS}`,
  UPDATE_SECTION_POSITION: `${MODULE_NAME}/${_MUTATES.UPDATE_SECTION_POSITION}`,
  UPDATE_SHEETS: `${MODULE_NAME}/${_MUTATES.UPDATE_SHEETS}`,
  UPDATE_SHEET_POSITION: `${MODULE_NAME}/${_MUTATES.UPDATE_SHEET_POSITION}`,
  SECTIONS: `${MODULE_NAME}/${_GETTERS.SECTIONS}`,
  BOOK_DETAIL: `${MODULE_NAME}/${_GETTERS.BOOK_DETAIL}`,
  BOOK_ID: `${MODULE_NAME}/${_GETTERS.BOOK_ID}`,
  SET_OBJECT_TYPE_SELECTED: `${MODULE_NAME}/${_MUTATES.SET_OBJECT_TYPE_SELECTED}`,
  TOGGLE_MENU_PROPERTIES: `${MODULE_NAME}/${_MUTATES.TOGGLE_MENU_PROPERTIES}`
};

export default {
  _GETTERS,
  _ACTIONS,
  _MUTATES
};
