export const MODULE_NAME = 'book';

const _GETTERS = {
  BOOK_DETAIL: 'bookDetail',
  BOOK_ID: 'bookId',
  SECTIONS: 'sections'
};

export const GETTERS = {
  SECTIONS: `${MODULE_NAME}/${_GETTERS.SECTIONS}`,
  BOOK_DETAIL: `${MODULE_NAME}/${_GETTERS.BOOK_DETAIL}`,
  BOOK_ID: `${MODULE_NAME}/${_GETTERS.BOOK_ID}`
};

const _ACTIONS = {
  GET_BOOK: 'getBook'
};

export const ACTIONS = {
  GET_BOOK: `${MODULE_NAME}/${_ACTIONS.GET_BOOK}`
};

const _MUTATES = {
  UPDATE_SECTIONS: 'updateSections',
  UPDATE_SECTION_POSITION: 'updateSectionPosition',
  UPDATE_SHEETS: 'updateSheets',
  UPDATE_SHEET_POSITION: 'updateSheetPosition',
  GET_BOOK_SUCCESS: 'getBookSuccess',
  ADD_SHEET: 'addSheet',
  DELETE_SECTION: 'deleteSection',
  DELETE_SHEET: 'deleteSheet',
  MOVE_SHEET: 'moveSheet',
  ADD_SECTION: 'addSection',
  EDIT_SECTION_NAME: 'editSectionName',
  SELECT_SHEET: 'selectSheet'
};

export const MUTATES = {
  GET_BOOK_SUCCESS: `${MODULE_NAME}/${_MUTATES.GET_BOOK_SUCCESS}`,
  UPDATE_SECTIONS: `${MODULE_NAME}/${_MUTATES.UPDATE_SECTIONS}`,
  UPDATE_SECTION_POSITION: `${MODULE_NAME}/${_MUTATES.UPDATE_SECTION_POSITION}`,
  UPDATE_SHEETS: `${MODULE_NAME}/${_MUTATES.UPDATE_SHEETS}`,
  UPDATE_SHEET_POSITION: `${MODULE_NAME}/${_MUTATES.UPDATE_SHEET_POSITION}`,
  SECTIONS: `${MODULE_NAME}/${_GETTERS.SECTIONS}`,
  BOOK_DETAIL: `${MODULE_NAME}/${_GETTERS.BOOK_DETAIL}`,
  BOOK_ID: `${MODULE_NAME}/${_GETTERS.BOOK_ID}`,
  ADD_SHEET: `${MODULE_NAME}/${_MUTATES.ADD_SHEET}`,
  DELETE_SECTION: `${MODULE_NAME}/${_MUTATES.DELETE_SECTION}`,
  DELETE_SHEET: `${MODULE_NAME}/${_MUTATES.DELETE_SHEET}`,
  MOVE_SHEET: `${MODULE_NAME}/${_MUTATES.MOVE_SHEET}`,
  ADD_SECTION: `${MODULE_NAME}/${_MUTATES.ADD_SECTION}`,
  EDIT_SECTION_NAME: `${MODULE_NAME}/${_MUTATES.EDIT_SECTION_NAME}`,
  SELECT_SHEET: `${MODULE_NAME}/${_MUTATES.SELECT_SHEET}`
};

export default {
  _GETTERS,
  _ACTIONS,
  _MUTATES
};
