export const MODULE_NAME = 'print';

const _GETTERS = {
  BOOK_ID: 'getBookId'
};

export const GETTERS = {
  BOOK_ID: `${MODULE_NAME}/${_GETTERS.BOOK_ID}`
};

const _ACTIONS = {
  GET_DATA_MAIN: 'getDataForMainPage',
  GET_DATA_EDIT: 'getDataForEditPage',
  GET_DATA_CANVAS: 'getDataForCanvas'
};

export const ACTIONS = {
  GET_DATA_MAIN: `${MODULE_NAME}/${_ACTIONS.GET_DATA_MAIN}`,
  GET_DATA_EDIT: `${MODULE_NAME}/${_ACTIONS.GET_DATA_EDIT}`,
  GET_DATA_CANVAS: `${MODULE_NAME}/${_ACTIONS.GET_DATA_CANVAS}`
};

const _MUTATES = {
  SET_BOOK_ID: 'setBookId',
  SET_CURRENT_SHEET: 'setCurrentSheet',
  SET_DEFAULT_THEME_ID: 'setDefaultThemeId',
  SET_SECTIONS_SHEETS: 'setSectionsSheets',
  SET_SECTIONS_SHEETS_EDIT: 'setSectionsSheetsEdit',
  SET_OBJECTS: 'setObjects',
  SET_BACKGROUNDS: 'setBackgrounds'
};

export const MUTATES = {
  SET_BOOK_ID: `${MODULE_NAME}/${_MUTATES.SET_BOOK_ID}`,
  SET_CURRENT_SHEET: `${MODULE_NAME}/${_MUTATES.SET_CURRENT_SHEET}`,
  SET_DEFAULT_THEME_ID: `${MODULE_NAME}/${_MUTATES.SET_DEFAULT_THEME_ID}`,
  SET_SECTIONS_SHEETS: `${MODULE_NAME}/${_MUTATES.SET_SECTIONS_SHEETS}`,
  SET_SECTIONS_SHEETS_EDIT: `${MODULE_NAME}/${_MUTATES.SET_SECTIONS_SHEETS_EDIT}`,
  SET_OBJECTS: `${MODULE_NAME}/${_MUTATES.SET_OBJECTS}`,
  SET_BACKGROUNDS: `${MODULE_NAME}/${_MUTATES.SET_BACKGROUNDS}`
};

export default {
  _GETTERS,
  _ACTIONS,
  _MUTATES
};
